Import Libraries

In [52]:
import pandas as pd
import numpy as np

Load Dataset

In [53]:
df = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

Display Dataset
df

Basic Dataset Information

In [54]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumns:")
print(df.columns.tolist())

Number of rows: 100
Number of columns: 13

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

First Few Records

In [55]:
df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

Last Few Records

In [56]:
df.tail()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

Random Sample

In [57]:
df.sample(5)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
45,1046,2026-01-03,Ananya Singh,Delhi,North,Books,The Alchemist,4,499,15,1696.60,3.8,Credit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
43,1044,2026-05-10,Hiba Sheikh,Chennai,South,Clothing,T-Shirt,2,799,5,1518.10,4.2,UPI

Dataset Information

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    str
 2   Customer          100 non-null    str
 3   City              100 non-null    str
 4   Region            100 non-null    str
 5   Category          100 non-null    str
 6   Product           100 non-null    str
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    str
dtypes: float64(2), int64(4), str(7)
memory usage: 10.3 KB

Statistical Summary

In [59]:
df.describe()

,Order_ID,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1050.500000,2.940000,1647.000000,6.500000,4472.629500,4.322000
std,29.011492,1.391315,970.054669,6.092718,3324.306691,0.414285
min,1001.000000,1.000000,499.000000,0.000000,449.100000,3.500000
25%,1025.750000,2.000000,799.000000,0.000000,1948.050000,4.100000
50%,1050.500000,3.000000,1499.000000,5.000000,3228.300000,4.300000
75%,1075.250000,4.000000,2499.000000,11.250000,6427.562500,4.700000
max,1100.000000,5.000000,3499.000000,15.000000,13995.000000,5.000000

Selecting Specific Columns

In [60]:
df["Product"]

0         Wireless Headphones
1               Running Shoes
2                  Power Bank
3         Mechanical Keyboard
4                 Smart Watch
               ...
95               Dumbbell Set
96                    T-Shirt
97            Electric Kettle
98    Machine Learning Basics
99      Data Science Handbook
Name: Product, Length: 100, dtype: str

Select multiple columns

In [61]:
df[["Order_ID", "Product", "Category", "Total_Sales"]]

    Order_ID                  Product        Category  Total_Sales
0       1001      Wireless Headphones     Electronics      4497.00
1       1002            Running Shoes          Sports      2799.00
2       1003               Power Bank     Electronics      2038.30
3       1004      Mechanical Keyboard     Electronics      9496.20
4       1005              Smart Watch     Electronics      3134.05
..       ...                      ...             ...          ...
95      1096             Dumbbell Set          Sports      9495.25
96      1097                  T-Shirt        Clothing       679.15
97      1098          Electric Kettle  Home & Kitchen      5996.00
98      1099  Machine Learning Basics           Books      1998.00
99      1100    Data Science Handbook           Books      4495.00

[100 rows x 4 columns]

Selecting Specific Rows

In [62]:
df.iloc[0:5]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

Selecting specific rows and columns:

In [63]:
df.iloc[0:5, 0:5]

   Order_ID  Order_Date      Customer       City Region
0      1001  2026-02-27     Kabir Ali  Hyderabad  South
1      1002  2026-01-24  Aditya Verma      Jammu  North
2      1003  2026-04-18    Sara Ahmed    Chennai  South
3      1004  2026-03-13     Kabir Ali    Lucknow  North
4      1005  2026-03-30   Priya Menon      Jammu  North

Using loc:

In [64]:
df.loc[0:4, ["Order_ID", "Product", "Total_Sales"]]

   Order_ID              Product  Total_Sales
0      1001  Wireless Headphones      4497.00
1      1002        Running Shoes      2799.00
2      1003           Power Bank      2038.30
3      1004  Mechanical Keyboard      9496.20
4      1005          Smart Watch      3134.05

Filtering Sales Greater Than ₹10,000

In [65]:
high_value_orders = df[df["Total_Sales"] > 10000]

high_value_orders[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
]

    Order_ID        Product        Category       City  Total_Sales
12      1013         Jacket        Clothing    Lucknow     10620.75
47      1048   Coffee Maker  Home & Kitchen    Lucknow     10497.00
48      1049  Running Shoes          Sports     Mumbai     13995.00
52      1053  Running Shoes          Sports  Hyderabad     13295.25
84      1085   Coffee Maker  Home & Kitchen  Hyderabad     12596.40
89      1090    Cricket Bat          Sports    Lucknow     12495.00

Filtering Sports Category

In [66]:
sports_orders = df[df["Category"] == "Sports"]

sports_orders[
    ["Order_ID", "Product", "City", "Quantity", "Total_Sales"]
]

    Order_ID        Product        City  Quantity  Total_Sales
1       1002  Running Shoes       Jammu         1      2799.00
11      1012    Cricket Bat  Chandigarh         2      4498.20
13      1014  Running Shoes      Jaipur         3      8397.00
16      1017    Cricket Bat   Hyderabad         3      7497.00
20      1021       Yoga Mat  Chandigarh         1       809.10
22      1023       Football      Jaipur         3      2157.30
23      1024  Running Shoes      Jaipur         1      2799.00
24      1025       Football     Chennai         5      3995.00
26      1027       Football  Chandigarh         5      3395.75
30      1031       Yoga Mat   Ahmedabad         1       764.15
35      1036       Yoga Mat    Srinagar         2      1798.00
37      1038   Dumbbell Set        Pune         5      9495.25
39      1040   Dumbbell Set   Ahmedabad         1      1999.00
48      1049  Running Shoes      Mumbai         5     13995.00
52      1053  Running Shoes   Hyderabad         5     13295.25
54      1055       Yoga Mat     Chennai         4      3056.60
55      1056   Dumbbell Set    Srinagar         2      3798.10
58      1059    Cricket Bat     Chennai         4      8496.60
59      1060   Dumbbell Set        Pune         3      5397.30
71      1072       Yoga Mat      Jaipur         5      4045.50
81      1082       Yoga Mat       Jammu         3      2292.45
82      1083       Football       Jammu         1       759.05
89      1090    Cricket Bat     Lucknow         5     12495.00
92      1093    Cricket Bat   Hyderabad         4      8496.60
95      1096   Dumbbell Set       Kochi         5      9495.25

Filtering Orders from Hyderabad

In [67]:
hyderabad_orders = df[df["City"] == "Hyderabad"]

hyderabad_orders[
    ["Order_ID", "Product", "Category", "Total_Sales"]
]

    Order_ID              Product        Category  Total_Sales
0       1001  Wireless Headphones     Electronics      4497.00
10      1011         Coffee Maker  Home & Kitchen      6998.00
16      1017          Cricket Bat          Sports      7497.00
28      1029  Wireless Headphones     Electronics      5696.20
52      1053        Running Shoes          Sports     13295.25
84      1085         Coffee Maker  Home & Kitchen     12596.40
92      1093          Cricket Bat          Sports      8496.60

Multiple Conditions

In [68]:
result = df[
    (df["Category"] == "Sports") &
    (df["City"] == "Hyderabad")
]

result[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
]

    Order_ID        Product Category       City  Total_Sales
16      1017    Cricket Bat   Sports  Hyderabad      7497.00
52      1053  Running Shoes   Sports  Hyderabad     13295.25
92      1093    Cricket Bat   Sports  Hyderabad      8496.60

Filtering by Payment Method

In [69]:
upi_orders = df[df["Payment_Method"] == "UPI"]

upi_orders[
    ["Order_ID", "Product", "Total_Sales", "Payment_Method"]
]

    Order_ID                  Product  Total_Sales Payment_Method
4       1005              Smart Watch      3134.05            UPI
10      1011             Coffee Maker      6998.00            UPI
13      1014            Running Shoes      8397.00            UPI
14      1015      Wireless Headphones      2998.00            UPI
15      1016            The Alchemist      1696.60            UPI
18      1019                   Jacket      7497.00            UPI
19      1020            Mixer Grinder      2999.00            UPI
23      1024            Running Shoes      2799.00            UPI
24      1025                 Football      3995.00            UPI
27      1028      Wireless Headphones      5696.20            UPI
29      1030       Python Programming      2996.00            UPI
31      1032            Atomic Habits      1078.20            UPI
33      1034                  T-Shirt      1598.00            UPI
36      1037               Power Bank      2038.30            UPI
38      1039            Mixer Grinder      5698.10            UPI
41      1042             Water Bottle      3495.00            UPI
43      1044                  T-Shirt      1518.10            UPI
46      1047           Wireless Mouse      3820.75            UPI
47      1048             Coffee Maker     10497.00            UPI
61      1062      Mechanical Keyboard      7497.00            UPI
63      1064            Atomic Habits      2396.00            UPI
68      1069           Wireless Mouse      1708.10            UPI
77      1078  Machine Learning Basics       899.10            UPI
86      1087            Atomic Habits      2036.60            UPI
96      1097                  T-Shirt       679.15            UPI
98      1099  Machine Learning Basics      1998.00            UPI

Sorting by Total Sales

In [70]:
df.sort_values(
    by="Total_Sales",
    ascending=False
)[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
].head(10)

    Order_ID              Product        Category        City  Total_Sales
48      1049        Running Shoes          Sports      Mumbai     13995.00
52      1053        Running Shoes          Sports   Hyderabad     13295.25
84      1085         Coffee Maker  Home & Kitchen   Hyderabad     12596.40
89      1090          Cricket Bat          Sports     Lucknow     12495.00
12      1013               Jacket        Clothing     Lucknow     10620.75
47      1048         Coffee Maker  Home & Kitchen     Lucknow     10497.00
69      1070               Jacket        Clothing       Delhi      9996.00
79      1080               Jacket        Clothing       Delhi      9996.00
51      1052  Mechanical Keyboard     Electronics  Chandigarh      9496.20
3       1004  Mechanical Keyboard     Electronics     Lucknow      9496.20

Lowest sales first

In [71]:
df.sort_values(
    by="Total_Sales",
    ascending=True
)[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
].head(10)

    Order_ID                  Product  Category        City  Total_Sales
5       1006            The Alchemist     Books       Kochi       449.10
62      1063            The Alchemist     Books  Chandigarh       449.10
73      1074            Atomic Habits     Books     Lucknow       539.10
96      1097                  T-Shirt  Clothing      Mumbai       679.15
60      1061       Python Programming     Books   Bengaluru       711.55
82      1083                 Football    Sports       Jammu       759.05
30      1031                 Yoga Mat    Sports   Ahmedabad       764.15
42      1043                  T-Shirt  Clothing      Jaipur       799.00
20      1021                 Yoga Mat    Sports  Chandigarh       809.10
77      1078  Machine Learning Basics     Books     Kolkata       899.10

Overall Sales Statistics

In [72]:
total_sales = df["Total_Sales"].sum()
average_sales = df["Total_Sales"].mean()
highest_sales = df["Total_Sales"].max()
lowest_sales = df["Total_Sales"].min()
total_quantity = df["Quantity"].sum()
number_of_orders = df["Order_ID"].nunique()

print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Average Sales     : ₹{average_sales:,.2f}")
print(f"Highest Sale      : ₹{highest_sales:,.2f}")
print(f"Lowest Sale       : ₹{lowest_sales:,.2f}")
print(f"Total Quantity    : {total_quantity}")
print(f"Number of Orders  : {number_of_orders}")

Total Sales       : ₹447,262.95
Average Sales     : ₹4,472.63
Highest Sale      : ₹13,995.00
Lowest Sale       : ₹449.10
Total Quantity    : 294
Number of Orders  : 100

Details of Highest-Sales Order

In [73]:
highest_order = df.loc[df["Total_Sales"].idxmax()]

print(highest_order)

Order_ID                     1049
Order_Date             2026-03-02
Customer             Ishita Gupta
City                       Mumbai
Region                       West
Category                   Sports
Product             Running Shoes
Quantity                        5
Unit_Price                   2799
Discount_Percent                0
Total_Sales               13995.0
Rating                        4.0
Payment_Method        Net Banking
Name: 48, dtype: object

Details of Lowest-Sales Order

In [74]:
lowest_order = df.loc[df["Total_Sales"].idxmin()]

print(lowest_order)

Order_ID                        1006
Order_Date                2026-01-21
Customer                   Manya Rao
City                           Kochi
Region                         South
Category                       Books
Product                The Alchemist
Quantity                           1
Unit_Price                       499
Discount_Percent                  10
Total_Sales                    449.1
Rating                           4.2
Payment_Method      Cash on Delivery
Name: 5, dtype: object

GroupBy – Category Analysis

In [75]:
category_analysis = df.groupby("Category").agg(
    Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean")
)

category_analysis

                Orders  Total_Quantity  Total_Sales  Average_Sales
Category
Books               21              60     36792.40    1752.019048
Clothing            14              39     69028.20    4930.585714
Electronics         19              57     92086.00    4846.631579
Home & Kitchen      21              59    113329.90    5396.661905
Sports              25              79    136026.45    5441.058000

Categories Sorted by Sales

In [76]:
category_analysis.sort_values(
    by="Total_Sales",
    ascending=False
)

                Orders  Total_Quantity  Total_Sales  Average_Sales
Category
Sports              25              79    136026.45    5441.058000
Home & Kitchen      21              59    113329.90    5396.661905
Electronics         19              57     92086.00    4846.631579
Clothing            14              39     69028.20    4930.585714
Books               21              60     36792.40    1752.019048

GroupBy – City Analysis

In [77]:
city_analysis = df.groupby("City").agg(
    Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean")
)

city_analysis

             Orders  Total_Quantity  Total_Sales  Average_Sales
City
Ahmedabad         6              12     14788.70    2464.783333
Bengaluru         4              14     13524.30    3381.075000
Bhubaneswar       1               2      6598.00    6598.000000
Chandigarh        8              22     34539.65    4317.456250
Chennai          10              29     47493.20    4749.320000
Delhi             6              18     30882.80    5147.133333
Hyderabad         7              25     59076.45    8439.492857
Jaipur            7              17     25534.00    3647.714286
Jammu             6              11     16059.75    2676.625000
Kochi             9              29     37257.50    4139.722222
Kolkata           7              24     20169.00    2881.285714
Lucknow           6              22     46194.65    7699.108333
Mumbai            8              23     41457.80    5182.225000
Pune             10              34     41908.55    4190.855000
Srinagar          5              12     11778.60    2355.720000

Cities Sorted by Total Sales

In [78]:
city_analysis.sort_values(
    by="Total_Sales",
    ascending=False
)

             Orders  Total_Quantity  Total_Sales  Average_Sales
City
Hyderabad         7              25     59076.45    8439.492857
Chennai          10              29     47493.20    4749.320000
Lucknow           6              22     46194.65    7699.108333
Pune             10              34     41908.55    4190.855000
Mumbai            8              23     41457.80    5182.225000
Kochi             9              29     37257.50    4139.722222
Chandigarh        8              22     34539.65    4317.456250
Delhi             6              18     30882.80    5147.133333
Jaipur            7              17     25534.00    3647.714286
Kolkata           7              24     20169.00    2881.285714
Jammu             6              11     16059.75    2676.625000
Ahmedabad         6              12     14788.70    2464.783333
Bengaluru         4              14     13524.30    3381.075000
Srinagar          5              12     11778.60    2355.720000
Bhubaneswar       1               2      6598.00    6598.000000

The top cities by total sales are:

In [79]:
city_analysis.sort_values(
    by="Total_Sales",
    ascending=False
).head(5)

           Orders  Total_Quantity  Total_Sales  Average_Sales
City
Hyderabad       7              25     59076.45    8439.492857
Chennai        10              29     47493.20    4749.320000
Lucknow         6              22     46194.65    7699.108333
Pune           10              34     41908.55    4190.855000
Mumbai          8              23     41457.80    5182.225000

GroupBy – Product Analysis

In [80]:
product_analysis = df.groupby("Product").agg(
    Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean")
)

product_analysis

                         Orders  Total_Quantity  Total_Sales  Average_Sales
Product
Atomic Habits                 6              21     11590.65    1931.775000
Coffee Maker                  7              16     51610.25    7372.892857
Cricket Bat                   5              18     41483.40    8296.680000
Data Science Handbook         1               5      4495.00    4495.000000
Dumbbell Set                  5              16     30184.90    6036.980000
Electric Kettle               5              19     26382.40    5276.480000
Football                      4              14     10307.10    2576.775000
Hoodie                        2               5      7675.20    3837.600000
Jacket                        5              20     47106.15    9421.230000
Jeans                         2               4      6456.60    3228.300000
Machine Learning Basics       4               6      5694.30    1423.575000
Mechanical Keyboard           3              11     26489.40    8829.800000
Mixer Grinder                 4               9     25341.55    6335.387500
Power Bank                    3               6      6474.60    2158.200000
Python Programming            4              11      7527.45    1881.862500
Running Shoes                 5              15     41285.25    8257.050000
Smart Watch                   3               5     15670.25    5223.416667
T-Shirt                       5              10      7790.25    1558.050000
The Alchemist                 6              17      7485.00    1247.500000
Water Bottle                  5              15      9995.70    1999.140000
Wireless Headphones           7              23     33877.40    4839.628571
Wireless Mouse                3              12      9574.35    3191.450000
Yoga Mat                      6              16     12765.80    2127.633333

Top 10 Products by Sales

In [81]:
top_products = product_analysis.sort_values(
    by="Total_Sales",
    ascending=False
).head(10)

top_products

                     Orders  Total_Quantity  Total_Sales  Average_Sales
Product
Coffee Maker              7              16     51610.25    7372.892857
Jacket                    5              20     47106.15    9421.230000
Cricket Bat               5              18     41483.40    8296.680000
Running Shoes             5              15     41285.25    8257.050000
Wireless Headphones       7              23     33877.40    4839.628571
Dumbbell Set              5              16     30184.90    6036.980000
Mechanical Keyboard       3              11     26489.40    8829.800000
Electric Kettle           5              19     26382.40    5276.480000
Mixer Grinder             4               9     25341.55    6335.387500
Smart Watch               3               5     15670.25    5223.416667

Product with Highest Average Sales

In [82]:
product_analysis.sort_values(
    by="Average_Sales",
    ascending=False
).head(10)

                     Orders  Total_Quantity  Total_Sales  Average_Sales
Product
Jacket                    5              20     47106.15    9421.230000
Mechanical Keyboard       3              11     26489.40    8829.800000
Cricket Bat               5              18     41483.40    8296.680000
Running Shoes             5              15     41285.25    8257.050000
Coffee Maker              7              16     51610.25    7372.892857
Mixer Grinder             4               9     25341.55    6335.387500
Dumbbell Set              5              16     30184.90    6036.980000
Electric Kettle           5              19     26382.40    5276.480000
Smart Watch               3               5     15670.25    5223.416667
Wireless Headphones       7              23     33877.40    4839.628571

GroupBy – Payment Method Analysis

In [83]:
payment_analysis = df.groupby("Payment_Method").agg(
    Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean")
)

payment_analysis

                  Orders  Total_Quantity  Total_Sales  Average_Sales
Payment_Method
Cash on Delivery      15              32     50123.30    3341.553333
Credit Card           22              65    106540.25    4842.738636
Debit Card            20              64     98064.90    4903.245000
Net Banking           17              63     96371.25    5668.897059
UPI                   26              70     96163.25    3698.586538

Payment Methods Sorted by Sales

In [84]:
payment_analysis.sort_values(
    by="Total_Sales",
    ascending=False
)

                  Orders  Total_Quantity  Total_Sales  Average_Sales
Payment_Method
Credit Card           22              65    106540.25    4842.738636
Debit Card            20              64     98064.90    4903.245000
Net Banking           17              63     96371.25    5668.897059
UPI                   26              70     96163.25    3698.586538
Cash on Delivery      15              32     50123.30    3341.553333

Region-Wise Analysis

In [85]:
region_analysis = df.groupby("Region").agg(
    Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean")
)

region_analysis.sort_values(
    by="Total_Sales",
    ascending=False
)

        Orders  Total_Quantity  Total_Sales  Average_Sales
Region
North       38             102    164989.45    4341.827632
South       30              97    157351.45    5245.048333
West        24              69     98155.05    4089.793750
East         8              26     26767.00    3345.875000

Find Orders Above Average Sales

In [86]:
average_sales = df["Total_Sales"].mean()

above_average = df[
    df["Total_Sales"] > average_sales
]

print("Average Sales:", average_sales)
print("Orders above average:", len(above_average))

above_average[
    ["Order_ID", "Product", "Category", "City", "Total_Sales"]
].head(10)

Average Sales: 4472.629500000001
Orders above average: 41

    Order_ID              Product        Category        City  Total_Sales
0       1001  Wireless Headphones     Electronics   Hyderabad      4497.00
3       1004  Mechanical Keyboard     Electronics     Lucknow      9496.20
7       1008               Hoodie        Clothing       Jammu      6076.20
8       1009      Electric Kettle  Home & Kitchen      Mumbai      4497.00
9       1010               Jacket        Clothing       Kochi      8996.40
10      1011         Coffee Maker  Home & Kitchen   Hyderabad      6998.00
11      1012          Cricket Bat          Sports  Chandigarh      4498.20
12      1013               Jacket        Clothing     Lucknow     10620.75
13      1014        Running Shoes          Sports      Jaipur      8397.00
16      1017          Cricket Bat          Sports   Hyderabad      7497.00

Find Large Quantity Orders

In [87]:
large_quantity_orders = df[df["Quantity"] > 3]

large_quantity_orders[
    ["Order_ID", "Product", "Quantity", "Total_Sales"]
]

    Order_ID                Product  Quantity  Total_Sales
3       1004    Mechanical Keyboard         4      9496.20
7       1008                 Hoodie         4      6076.20
9       1010                 Jacket         4      8996.40
12      1013                 Jacket         5     10620.75
15      1016          The Alchemist         4      1696.60
24      1025               Football         5      3995.00
26      1027               Football         5      3395.75
27      1028    Wireless Headphones         4      5696.20
28      1029    Wireless Headphones         4      5696.20
29      1030     Python Programming         4      2996.00
37      1038           Dumbbell Set         5      9495.25
41      1042           Water Bottle         5      3495.00
45      1046          The Alchemist         4      1696.60
46      1047         Wireless Mouse         5      3820.75
48      1049          Running Shoes         5     13995.00
49      1050                T-Shirt         4      3196.00
51      1052    Mechanical Keyboard         4      9496.20
52      1053          Running Shoes         5     13295.25
54      1055               Yoga Mat         4      3056.60
58      1059            Cricket Bat         4      8496.60
63      1064          Atomic Habits         4      2396.00
66      1067          The Alchemist         5      2245.50
69      1070                 Jacket         4      9996.00
70      1071           Water Bottle         4      2516.40
71      1072               Yoga Mat         5      4045.50
72      1073          Atomic Habits         5      2545.75
75      1076    Wireless Headphones         4      5996.00
76      1077        Electric Kettle         4      5696.20
79      1080                 Jacket         4      9996.00
80      1081        Electric Kettle         5      6370.75
83      1084         Wireless Mouse         5      4045.50
84      1085           Coffee Maker         4     12596.40
86      1087          Atomic Habits         4      2036.60
87      1088     Python Programming         4      2546.60
89      1090            Cricket Bat         5     12495.00
90      1091          Atomic Habits         5      2995.00
92      1093            Cricket Bat         4      8496.60
95      1096           Dumbbell Set         5      9495.25
97      1098        Electric Kettle         4      5996.00
99      1100  Data Science Handbook         5      4495.00

Find Highly Rated Products/Orders

In [88]:
high_rated = df[df["Rating"] >= 4.5]

high_rated[
    ["Order_ID", "Product", "Category", "Rating", "Total_Sales"]
]

    Order_ID                  Product        Category  Rating  Total_Sales
2       1003               Power Bank     Electronics     4.6      2038.30
9       1010                   Jacket        Clothing     4.7      8996.40
11      1012              Cricket Bat          Sports     4.6      4498.20
12      1013                   Jacket        Clothing     4.8     10620.75
13      1014            Running Shoes          Sports     4.6      8397.00
14      1015      Wireless Headphones     Electronics     4.8      2998.00
18      1019                   Jacket        Clothing     4.7      7497.00
20      1021                 Yoga Mat          Sports     4.7       809.10
21      1022            The Alchemist           Books     4.5       948.10
24      1025                 Football          Sports     5.0      3995.00
26      1027                 Football          Sports     4.6      3395.75
27      1028      Wireless Headphones     Electronics     4.6      5696.20
31      1032            Atomic Habits           Books     4.5      1078.20
32      1033            Mixer Grinder  Home & Kitchen     4.7      8097.30
33      1034                  T-Shirt        Clothing     4.7      1598.00
34      1035             Coffee Maker  Home & Kitchen     4.7      2974.15
35      1036                 Yoga Mat          Sports     5.0      1798.00
36      1037               Power Bank     Electronics     4.8      2038.30
37      1038             Dumbbell Set          Sports     5.0      9495.25
39      1040             Dumbbell Set          Sports     4.7      1999.00
40      1041             Coffee Maker  Home & Kitchen     4.6      6648.10
47      1048             Coffee Maker  Home & Kitchen     5.0     10497.00
55      1056             Dumbbell Set          Sports     5.0      3798.10
56      1057             Coffee Maker  Home & Kitchen     4.5      8922.45
57      1058             Water Bottle  Home & Kitchen     4.5      1398.00
59      1060             Dumbbell Set          Sports     5.0      5397.30
60      1061       Python Programming           Books     5.0       711.55
62      1063            The Alchemist           Books     4.8       449.10
64      1065       Python Programming           Books     4.7      1273.30
65      1066              Smart Watch     Electronics     4.7      5938.20
68      1069           Wireless Mouse     Electronics     4.7      1708.10
70      1071             Water Bottle  Home & Kitchen     4.5      2516.40
72      1073            Atomic Habits           Books     4.6      2545.75
73      1074            Atomic Habits           Books     5.0       539.10
74      1075                    Jeans        Clothing     4.5      3228.30
76      1077          Electric Kettle  Home & Kitchen     4.5      5696.20
77      1078  Machine Learning Basics           Books     4.7       899.10
79      1080                   Jacket        Clothing     4.6      9996.00
81      1082                 Yoga Mat          Sports     4.5      2292.45
85      1086                    Jeans        Clothing     4.8      3228.30
87      1088       Python Programming           Books     4.5      2546.60
90      1091            Atomic Habits           Books     5.0      2995.00
92      1093              Cricket Bat          Sports     4.5      8496.60
94      1095               Power Bank     Electronics     4.6      2398.00
99      1100    Data Science Handbook           Books     4.8      4495.00

Top 10 Individual Orders

In [89]:
top_orders = df.sort_values(
    by="Total_Sales",
    ascending=False
).head(10)

top_orders[
    [
        "Order_ID",
        "Product",
        "Category",
        "City",
        "Quantity",
        "Total_Sales",
        "Payment_Method"
    ]
]

,Order_ID,Product,Category,City,Quantity,Total_Sales,Payment_Method
48,1049,Running Shoes,Sports,Mumbai,5,13995.00,Net Banking
52,1053,Running Shoes,Sports,Hyderabad,5,13295.25,Credit Card
84,1085,Coffee Maker,Home & Kitchen,Hyderabad,4,12596.40,Net Banking
89,1090,Cricket Bat,Sports,Lucknow,5,12495.00,Credit Card
12,1013,Jacket,Clothing,Lucknow,5,10620.75,Net Banking
47,1048,Coffee Maker,Home & Kitchen,Lucknow,3,10497.00,UPI
69,1070,Jacket,Clothing,Delhi,4,9996.00,Net Banking
79,1080,Jacket,Clothing,Delhi,4,9996.00,Debit Card
51,1052,Mechanical Keyboard,Electronics,Chandigarh,4,9496.20,Debit Card
3,1004,Mechanical Keyboard,Electronics,Lucknow,4,9496.20,Debit Card

Category and City Combined Analysis

In [90]:
category_city = df.groupby(
    ["Category", "City"]
).agg(
    Orders=("Order_ID", "count"),
    Quantity=("Quantity", "sum"),
    Total_Sales=("Total_Sales", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

category_city.head(15)

                           Orders  Quantity  Total_Sales
Category       City
Sports         Hyderabad        3        12     29288.85
Clothing       Delhi            3        10     21590.00
Electronics    Chandigarh       3        11     19689.40
Home & Kitchen Hyderabad        2         6     19594.40
               Pune             4        13     17707.90
Sports         Jaipur           4        12     17398.80
               Chennai          3        13     15548.20
Clothing       Kochi            3         8     15453.00
Home & Kitchen Chennai          3         5     14895.60
Sports         Pune             2         8     14892.55
               Mumbai           1         5     13995.00
Home & Kitchen Mumbai           2         6     13044.15
Sports         Lucknow          1         5     12495.00
Clothing       Lucknow          1         5     10620.75
Home & Kitchen Lucknow          1         3     10497.00

Payment Method and Category Analysis

In [91]:
payment_category = df.groupby(
    ["Payment_Method", "Category"]
).agg(
    Orders=("Order_ID", "count"),
    Total_Sales=("Total_Sales", "sum")
).sort_values(
    by="Total_Sales",
    ascending=False
)

payment_category

                                 Orders  Total_Sales
Payment_Method   Category
Credit Card      Sports              10     59341.30
Net Banking      Home & Kitchen       5     32180.25
Debit Card       Electronics          5     31883.40
Net Banking      Sports               5     30101.65
UPI              Home & Kitchen       5     29687.10
                 Electronics          7     26892.40
Debit Card       Home & Kitchen       5     26209.85
Net Banking      Clothing             3     23812.75
Debit Card       Sports               4     19337.85
Cash on Delivery Electronics          4     16519.00
UPI              Sports               3     15191.00
Credit Card      Clothing             2     15072.60
UPI              Books                7     13100.50
Credit Card      Home & Kitchen       3     12919.30
Cash on Delivery Home & Kitchen       3     12333.40
Credit Card      Electronics          2     12294.20
Cash on Delivery Sports               3     12054.65
UPI              Clothing             4     11292.25
Debit Card       Clothing             2     10795.00
                 Books                4      9838.80
Cash on Delivery Clothing             3      8055.60
Credit Card      Books                5      6912.85
Net Banking      Books                3      5779.60
                 Electronics          1      4497.00
Cash on Delivery Books                2      1160.65